# Site settings
## Change the values as needed.
title: WalterInSH
email: walterinsh@icloud.com
description: "WalterInSH's Home"
keywords: "walterinsh, blog, java, reading"
#url: "http://walterinsh.github.io"
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
paginate_path: "page:num"
# Build settings
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: WalterInSH
  twitter: WalterInSH
  email: walterinsh@icloud.com
  github: WalterInSH/
exclude:
  - bower_components
  - README.md
full_name: Walter Zhang
gems:
  - redcarpet
  - jekyll-paginate
